//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protoFile/ProtoMsg.proto
namespace chanyu
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginProto")]
  public partial class LoginProto : global::ProtoBuf.IExtensible
  {
    public LoginProto() {}
    
    private int _thirdpartyid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thirdpartyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int thirdpartyid
    {
      get { return _thirdpartyid; }
      set { _thirdpartyid = value; }
    }
    private string _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _loginsession;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"loginsession", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginsession
    {
      get { return _loginsession; }
      set { _loginsession = value; }
    }

    private int _serverid = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }

    private string _usertype = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"usertype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string usertype
    {
      get { return _usertype; }
      set { _usertype = value; }
    }

    private string _stringValue1 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stringValue1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stringValue1
    {
      get { return _stringValue1; }
      set { _stringValue1 = value; }
    }

    private string _systemInfo = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"systemInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string systemInfo
    {
      get { return _systemInfo; }
      set { _systemInfo = value; }
    }

    private string _clientVersion = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"clientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientVersion
    {
      get { return _clientVersion; }
      set { _clientVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameProto")]
  public partial class EnterGameProto : global::ProtoBuf.IExtensible
  {
    public EnterGameProto() {}
    
    private int _cid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _isMale;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isMale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isMale
    {
      get { return _isMale; }
      set { _isMale = value; }
    }
    private double _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _crystal;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"crystal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crystal
    {
      get { return _crystal; }
      set { _crystal = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _stamina;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"stamina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stamina
    {
      get { return _stamina; }
      set { _stamina = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private double _exp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _icon;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }

    private int _viplevel = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"viplevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int viplevel
    {
      get { return _viplevel; }
      set { _viplevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailSendProto")]
  public partial class MailSendProto : global::ProtoBuf.IExtensible
  {
    public MailSendProto() {}
    
    private int _targetId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}