//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageConfig.proto
namespace m
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageConfig")]
  public partial class StageConfig : global::ProtoBuf.IExtensible
  {
    public StageConfig() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _author;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"author", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string author
    {
      get { return _author; }
      set { _author = value; }
    }
    private string _PoemItem;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PoemItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PoemItem
    {
      get { return _PoemItem; }
      set { _PoemItem = value; }
    }
    private string _PoemText;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PoemText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PoemText
    {
      get { return _PoemText; }
      set { _PoemText = value; }
    }
    private string _annotation;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"annotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string annotation
    {
      get { return _annotation; }
      set { _annotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}